### ISSUE TITLE
Make sure to use db.ping() basically everywhere

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#102]
We still have a few "lost connection to MySQL server" errors happening sporadically. To combat those, we should ping pretty much every time before we write to the db. In this case, we should probably ping before we start processing the logs upload. Stack trace follows.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./wp1/logs.py", line 194, in update_log_page_for_project
    edits = generate_log_edits(wikidb, wp10db, project_name, log_map)
  File "./wp1/logs.py", line 179, in generate_log_edits
    wikidb, wp10db, project_name, dt, logs)
  File "./wp1/logs.py", line 170, in section_for_date
    template_data = get_section_data(wikidb, wp10db, project_name, dt, logs)
  File "./wp1/logs.py", line 125, in get_section_data
    wp10db, log.l_namespace, log.l_article, log.l_revision_timestamp)
  File "./wp1/logs.py", line 38, in move_target
    ''', (ns, article, db_timestamp))
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

**Comment by audiodude** [comment]
Or maybe these are unavoidable?
