### ISSUE TITLE
Bot stopped running on Video game project

### ISSUE THREAD

**Issue by PresNCode** [openzim/wp1#703]
https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Video_game_articles_by_quality_log hasn't been updated since February 28. The bot is still running, but doesn't run for that project.

I tried doing a manual update on the openzim website, but it gets stuck at "Progress: Your job is almost finished, just wrapping up some tasks" and never finishes.

**Comment by audiodude** [comment]
Found this in the logs when doing a manual update:

```
01:15:27 [Job 767d381a-be7c-4b6c-a6b3-71a27bd6f759]: exception raised while executing (wp1.logic.project.update_project_by_name)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 1359, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 1178, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.9/site-packages/rq/job.py", line 1215, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/usr/src/app/./wp1/logic/project.py", line 78, in update_project_by_name
    update_project(wikidb,
  File "/usr/src/app/./wp1/logic/project.py", line 615, in update_project
    update_project_assessments(wikidb,
  File "/usr/src/app/./wp1/logic/project.py", line 370, in update_project_assessments
    process_unseen_articles(wikidb, wp10db, project, old_ratings, seen)
  File "/usr/src/app/./wp1/logic/project.py", line 499, in process_unseen_articles
    move_data = logic_page.get_move_data(wp10db, wikidb, ns, title,
  File "/usr/src/app/./wp1/logic/page.py", line 123, in get_move_data
    moves = _get_moves_from_api(wp10db, namespace, title, timestamp_dt)
  File "/usr/src/app/./wp1/logic/page.py", line 92, in _get_moves_from_api
    title_with_ns = logic_util.title_for_api(wp10db, namespace, title)
  File "/usr/src/app/./wp1/logic/util.py", line 68, in title_for_api
    ns_str = int_to_ns(wp10db)[namespace].decode('utf-8')
KeyError: 2300
```

Some kind of problem with a namespace that we're not aware of?

**Comment by audiodude** [comment]
I updated `namespacename` in the db. Let's see if this is fixed in the next update.

**Comment by audiodude** [comment]
Looks like this is fixed:

![image](https://github.com/openzim/wp1/assets/57832/1f02c149-4a8f-4953-8e53-ebc54bd63111)

**Comment by PresNCode** [comment]
Thank you!
