### ISSUE TITLE
Catholicism log update failed with a unique 'None-type' error

### ISSUE THREAD

**Issue by audiodude** [openzim/wp1#93]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./wp1/logs.py", line 194, in update_log_page_for_project
    edits = generate_log_edits(wikidb, wp10db, project_name, log_map)
  File "./wp1/logs.py", line 179, in generate_log_edits
    wikidb, wp10db, project_name, dt, logs)
  File "./wp1/logs.py", line 172, in section_for_date
    return template.render(template_data)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./wp1/templates/log_section.jinja2", line 12, in top-level template code
    * '''[[{{name[art]}}]]''' ([[{{talk[art]}}|talk]]) reassessed. {{quality_and_importance(art)}}
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "./wp1/templates/log_helpers.jinja2", line 31, in template
    {{ ' ' }}{{quality(art)}} {{revs(art, 'quality')}}
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "./wp1/templates/log_helpers.jinja2", line 14, in template
    {% if l[art]['quality'].l_old.decode('utf-8') == 'NotA-Class' -%}
jinja2.exceptions.UndefinedError: 'None' has no attribute 'decode'
```

We assume that no log entry has a None for l_old, because of the way they are set up in the update job. Need to investigate.

**Comment by audiodude** [comment]
Saw this happen with Military History today too:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./wp1/logs.py", line 194, in update_log_page_for_project
    edits = generate_log_edits(wikidb, wp10db, project_name, log_map)
  File "./wp1/logs.py", line 179, in generate_log_edits
    wikidb, wp10db, project_name, dt, logs)
  File "./wp1/logs.py", line 172, in section_for_date
    return template.render(template_data)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./wp1/templates/log_section.jinja2", line 18, in top-level template code
    * '''[[{{name[art]}}]]''' ([[{{talk[art]}}|talk]]) assessed. {{quality_and_importance(art)}}
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "./wp1/templates/log_helpers.jinja2", line 34, in template
    {{ ' ' }}{{importance(art)}} {{revs(art, 'importance')}}
  File "/usr/local/lib/python3.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "./wp1/templates/log_helpers.jinja2", line 23, in template
    Importance assessed as '''{{l[art]['importance'].l_new.decode('utf-8')}}'''.
jinja2.exceptions.UndefinedError: 'None' has no attribute 'decode'
```

**Comment by audiodude** [comment]
I think the reason for this is that we assume that the "project cleanup" task, part of the update job, runs for all projects. So all projects should have NotA-Class instead of a literal NULL for their 'new' and 'old' log values. However this is clearly not always the case.
